name: flutter_audio_capture
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.ymd.flutter_audio_capture
    pluginClass: FlutterAudioCapturePlugin
